//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.04 at 05:14:05 PM WAT 
//


package ihvn.data.extractor.model.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ihvn.data.extractor.model.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ihvn.data.extractor.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link MessageHeaderType }
     * 
     */
    public MessageHeaderType createMessageHeaderType() {
        return new MessageHeaderType();
    }

    /**
     * Create an instance of {@link MessageDataType }
     * 
     */
    public MessageDataType createMessageDataType() {
        return new MessageDataType();
    }

    /**
     * Create an instance of {@link DemographicsType }
     * 
     */
    public DemographicsType createDemographicsType() {
        return new DemographicsType();
    }

    /**
     * Create an instance of {@link EncounterProviderType }
     * 
     */
    public EncounterProviderType createEncounterProviderType() {
        return new EncounterProviderType();
    }

    /**
     * Create an instance of {@link PatientProgramType }
     * 
     */
    public PatientProgramType createPatientProgramType() {
        return new PatientProgramType();
    }

    /**
     * Create an instance of {@link PatientBiometricType }
     * 
     */
    public PatientBiometricType createPatientBiometricType() {
        return new PatientBiometricType();
    }

    /**
     * Create an instance of {@link VisitType }
     * 
     */
    public VisitType createVisitType() {
        return new VisitType();
    }

    /**
     * Create an instance of {@link ObsType }
     * 
     */
    public ObsType createObsType() {
        return new ObsType();
    }

    /**
     * Create an instance of {@link EncounterType }
     * 
     */
    public EncounterType createEncounterType() {
        return new EncounterType();
    }

    /**
     * Create an instance of {@link PatientIdentifierType }
     * 
     */
    public PatientIdentifierType createPatientIdentifierType() {
        return new PatientIdentifierType();
    }

}
